export const vereinsmeisterData = [
    { year: "2014", first: "Benno Moser", second: "Nico Zorn", third: "Leonid Krol" },
    { year: "2013", first: "Nico Zorn", second: "Heinz Meyer", third: "Nicolas Mesot" },
    { year: "2012", first: "Jochen Bahner", second: "Nico Zorn", third: "Benno Moser" },
    { year: "2011", first: "Jochen Bahner", second: "Benno Moser", third: "Wolfgang Scheina" },
    { year: "2010", first: "Stefan Frommherz", second: "Wolfgang Scheina", third: "Jochen Bahner" },
    { year: "2009", first: "Stefan Frommherz", second: "Roland Bahner", third: "Wolfgang Scheina" },
    { year: "2008", first: "Thomas Schmidt", second: "Stefan Frommherz", third: "Roland Bahner" },
    { year: "2007", first: "Thomas Schmidt", second: "Bernhard Bürgin", third: "Roland Bahner" },
    { year: "2006", first: "Bernhard Bürgin", second: "Wolfgang Scheina", third: "Roland Bahner" },
    { year: "2005", first: "Wolfgang Scheina", second: "Josef Jurgetz", third: "Roland Bahner" },
    { year: "2004", first: "Josef Jurgetz", second: "Wolfgang Scheina", third: "Elmar Kohlhöfer" },
    { year: "2003", first: "Bernhard Bürgin", second: "Roland Bahner", third: "Wolfgang Scheina" },
    { year: "2002", first: "Wolfgang Scheina", second: "Bernhard Bürgin", third: "Roland Bahner" },
    { year: "2001", first: "Bernhard Bürgin", second: "Roland Bahner", third: "Wolfgang Scheina" },
    { year: "1993", first: "Karl-Heinz Pflaum", second: "", third: "" },
  ];
  
  export const pokalsiegerData = [
    { year: "2014", winner: "Nico Zorn" },
    { year: "2012", winner: "Stefan Frommherz" },
    { year: "2011", winner: "Tobias Oelschlegel" },
    { year: "2010", winner: "Wolfgang Scheina" },
    { year: "2009", winner: "Tobias Oelschlegel" },
    { year: "2008", winner: "Stefan Frommherz" },
    { year: "2007", winner: "Bernhard Bürgin" },
    { year: "2006", winner: "Bernhard Bürgin" },
    { year: "2005", winner: "Roland Bahner" },
    { year: "2004", winner: "Bernhard Bürgin" },
    { year: "2003", winner: "Roland Bahner" },
    { year: "2002", winner: "Bernhard Bürgin" },
    { year: "2001", winner: "Bernhard Bürgin" },
    { year: "2000", winner: "Bernhard Bürgin" },
    { year: "1993", winner: "Karl-Heinz Pflaum" },
    { year: "1992", winner: "Karl-Heinz Pflaum" },
    { year: "1991", winner: "Karl-Heinz Pflaum" },
    { year: "1989", winner: "K.D. Oeschger" },
    { year: "1988", winner: "K.D. Oeschger" },
    { year: "1987", winner: "K.D. Oeschger" },
    { year: "1986", winner: "Franz Baumgartner" },
  ];
  
  export const blitzsiegerData = [
    { year: "2017", winner: "Tobias Oelschlegel" },
    { year: "2016", winner: "Tobias Oelschlegel" },
    { year: "2014", winner: "Bernhard Bürgin" },
    { year: "2012", winner: "Jochen Bahner" },
    { year: "2011", winner: "Tobias Oelschlegel" },
    { year: "2010", winner: "Tobias Oelschlegel" },
    { year: "2009", winner: "Jochen Bahner" },
    { year: "2008", winner: "Bernhard Bürgin" },
    { year: "2007", winner: "Stefan Frommherz" },
    { year: "2006", winner: "Elmar Kohlhöfer" },
    { year: "2005", winner: "Roland Bahner" },
    { year: "2004", winner: "Wolfgang Scheina" },
    { year: "2003", winner: "Karl-Heinz Pflaum" },
    { year: "1993", winner: "Karl-Heinz Pflaum" },
    { year: "1992", winner: "Karl-Heinz Pflaum" },
    { year: "1991", winner: "Karl-Heinz Pflaum" },
    { year: "1990", winner: "K.D. Oeschger" },
    { year: "1989", winner: "K.D. Oeschger" },
    { year: "1988", winner: "K.D. Oeschger" },
    { year: "1987", winner: "K.D. Oeschger" },
  ];